"""Add AI analysis fields and report table

Revision ID: 36df710865ae
Revises: v2_add_investor_password
Create Date: 2026-03-16 17:35:38.211661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36df710865ae'
down_revision = 'v2_add_investor_password'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_performance_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('system_version', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('negative_trades_root_cause', sa.Text(), nullable=True),
    sa.Column('positive_trades_success_factors', sa.Text(), nullable=True),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('session_comparison', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('heatmap_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('trades', sa.Column('opening_ai_analysis', sa.Text(), nullable=True))
    op.add_column('trades', sa.Column('closing_ai_analysis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'closing_ai_analysis')
    op.drop_column('trades', 'opening_ai_analysis')
    op.drop_table('ai_performance_reports')
    # ### end Alembic commands ###
