"""Add macro events table

Revision ID: 921a65135c87
Revises: 36df710865ae
Create Date: 2026-03-16 18:12:11.889557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '921a65135c87'
down_revision = '36df710865ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('impact', sa.String(length=10), nullable=False),
    sa.Column('actual', sa.String(), nullable=True),
    sa.Column('forecast', sa.String(), nullable=True),
    sa.Column('previous', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('macro_events')
    # ### end Alembic commands ###
